### ISSUE TITLE
[PE-D][Tester D] "add grade" overwrites the previous grade

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2113-W12-1/tp#107]
![image.png](https://raw.githubusercontent.com/djleong01/ped/main/files/7a78dc36-b544-4254-b632-ce6acc48319d.png)

What is the difference between "add grade" and "change grade" then if i can use "add" to edit my grades

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: djleong01/ped#4

**Comment by ZhangWenyue3325** [comment]
After adding a grade to the course, the user will try to change or delete it instead of adding it again. Although "add" and "change " commands are calling the same methods, different command words are more user-friendly as they are closer to users' usual behavior.
